#!/data/data/com.termux/files/usr/bin/bash

echo "Installing all necessary packages...."

pkg install zsh git curl vim cowsay gdb man wget radare2 tree psmisc python python2 openssh irssi clang coreutils binutils dnsutils nmap nano figlet htop tmux file net-tools gawk openssl-tool pwgen procps screenfetch make poppler termux-tools -y

echo "Installing ipython and youtube-dl using pip"
pip install ipython youtube-dl

echo "Done installing packages!"
mkdir ~/bin
echo 'PATH="$HOME/bin:$PATH"' >> "$HOME/.zshrc"
touch .vimrc .gdbinit
echo -e "set disassembly-flavor intel" >> ~/.gdbinit
echo -e "set number\nsyntax on" >> ~/.vimrc
echo "Now Adding extra-keys"
mkdir $HOME/.termux/; echo "extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]" >> $HOME/.termux/termux.properties
echo "Downloading powerline fonts!"
curl -fsSL -o ~/.termux/font.ttf 'https://github.com/romkatv/dotfiles-public/raw/master/.local/share/fonts/NerdFonts/MesloLGS%20NF%20Regular.ttf'
termux-reload-settings

echo "Now installing oh-my-zsh"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "if test -t 1; then
exec zsh
fi" >> ~/.bashrc

source ~/.bashrc

