#!/data/data/com.termux/files/usr/bin/bash

echo "Installing all necessary packages...."

pkg install zsh git curl vim cowsay gdb man wget radare2 tree psmisc python python2 openssh irssi clang coreutils binutils dnsutils nmap nano figlet htop tmux file net-tools gawk openssl-tool pwgen procps screenfetch make poppler termux-tools -y

echo "Installing ipython and youtube-dl using pip"
pip install ipython youtube-dl

echo "Done installing packages!"
echo "Now Adding extra-keys"
mkdir $HOME/.termux/; echo "extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]" >> $HOME/.termux/termux.properties
echo "Downloading powerline fonts!"
curl -fsSl -o ~/.termux/font.ttf https://t.co/wz1dhhISoD
termux-reload-settings

echo "Now installing oh-my-zsh"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "if test -t 1; then
exec zsh
fi" >> ~/.bashrc

source ~/.bashrc

