#!/data/data/com.termux/files/usr/bin/bash

echo "Updating repository lists.."
apt update && apt upgrade -y

echo "Installing oh-my-zsh"
apt install zsh git curl
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "if test -t 1; then exec zsh
fi" >> ~/.bashrc

source ~/.bashrc

echo "Now installing all necessary packages...."
apt install cowsay gdb man wget radare2 tree python python2 openssh irssi php clang apache2 coreutils binutils dnsutils nmap nano toilet figlet htop  -y

echo "Installing ipython.."
pip install ipython

echo "Done installing packages!"

